<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>{{ $data->shipping->name }} Invoice</title>
</head>
<body>

	<h1 style="text-align: center; font-family: sans-serif;">Dev Store</h1>
	<h4 style="text-align: right; font-family: sans-serif;">Invoice Code : {{ $data->order_code }}</h4>
	<hr><br>

	<h3 style="font-family: sans-serif;">Items List</h3>

	<table cellspacing="0" cellpadding="10" style="border: 1px solid #bbb; font-family: sans-serif;">
		<thead>
			<tr>
				<td style="border: 1px solid #bbb; font-weight: bold;">NO</td>
				<td style="border: 1px solid #bbb; font-weight: bold;">PRODUCT NAME</td>
				<td style="border: 1px solid #bbb; font-weight: bold;">PRODUCT PRICE</td>
				<td style="border: 1px solid #bbb; font-weight: bold;">QTY</td>
			</tr>
		</thead>
		<tbody>
			@php
				$i = 1;
			@endphp
			@foreach($cart as $c)
				@php
					$singlePrice = number_format($c->product->product_price, 2, ',', '.');
				@endphp
				<tr>
					<td style="border: 1px solid #bbb;">{{ $i }}</td>
					<td style="border: 1px solid #bbb;">{{ $c->product->product_name }}</td>
					<td style="border: 1px solid #bbb;">{{ 'Rp.' . $singlePrice }}</td>
					<td style="border: 1px solid #bbb;">{{ $c->qty }}</td>
				</tr>
			@php
				$i++;
			@endphp
			@endforeach
		</tbody>
	</table>
	
	<br><br>
	<h3 style="font-family: sans-serif;">Summary</h3>
	<table style="border: 1px solid #bbb; font-family: sans-serif;" cellspacing="0" cellpadding="10">
		<thead>
			<tr>
				<th style="border: 1px solid #bbb;">NAME</th>
				<th style="border: 1px solid #bbb;">ORDER CODE</th>
				<th style="border: 1px solid #bbb;">SUBTOTAL</th>
				<th style="border: 1px solid #bbb;">DISCOUNT</th>
				<th style="border: 1px solid #bbb;">TOTAL</th>
			</tr>
		</thead>
		<tbody>
			@php
				$subtotal = number_format($data->total, 2, ',', '.');
				$discount = number_format($data->discount, 2, ',', '.');
				$afterPrice = $data->total - $data->discount;
				$total = number_format($afterPrice, 2, ',', '.');
			@endphp
			<tr>
				<td style="border: 1px solid #bbb;">{{ $data->shipping->name }}</td>
				<td style="border: 1px solid #bbb;">{{ $data->order_code }}</td>
				<td style="border: 1px solid #bbb;">{{ 'Rp.' . $subtotal }}</td>
				<td style="border: 1px solid #bbb;">{{ 'Rp.' . $discount }}</td>
				<td style="border: 1px solid #bbb;">{{ 'Rp.' . $total }}</td>
			</tr>
		</tbody>
	</table>

	<br><br>
	<h3 style="font-family: sans-serif;">Shipping Detail</h3>
	<table style="border: 1px solid #bbb; font-family: sans-serif;" cellpadding="10" cellspacing="0">
		<thead>
			<tr>
				<th style="border: 1px solid #bbb; font-weight: bold;">NAME</th>
				<th style="border: 1px solid #bbb; font-weight: bold;">PHONE</th>
				<th style="border: 1px solid #bbb; font-weight: bold;">COUNTRY</th>
				<th style="border: 1px solid #bbb; font-weight: bold;">PROVINCE</th>
				<th style="border: 1px solid #bbb; font-weight: bold;">CITY</th>
				<th style="border: 1px solid #bbb; font-weight: bold;">ADDRESS</th>
			</tr>
		</thead>
		<tbody>
			<tr>
				<td style="border: 1px solid #bbb;">{{ $data->shipping->name }}</td>
				<td style="border: 1px solid #bbb;">{{ $data->shipping->phone }}</td>
				<td style="border: 1px solid #bbb;">{{ $data->shipping->country }}</td>
				<td style="border: 1px solid #bbb;">{{ $data->shipping->province }}</td>
				<td style="border: 1px solid #bbb;">{{ $data->shipping->city }}</td>
				<td style="border: 1px solid #bbb;">{{ $data->shipping->address }}</td>
			</tr>
		</tbody>
	</table>

	<br><br>
	<p style="text-align: right; font-family: sans-serif; font-size: 16px; line-height: 32px;">
		Thank You for shopping at our store, <br>
		Dev Store Admin <br>
		Have a nice day :)
	</p>

	<br><br>
	<p style="font-family: sans-serif; line-height: 32px;">*This invoice is automatically generated by Dev Store. <br> *The invoice only used to check your shopping detail, not for payment evidence!</p>
	
</body>
</html>